language: node_js
node_js:
 - "node"
install:
 - yarn install
before_script:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
script:
 - yarn run lint
 - yarn build
 - yarn run travis-karma-browserstack
after_script:
 - yarn run post-coveralls
 - yarn add -D codacy-coverage
 - yarn run send-codacy
