version: 1
update_configs:
  - package_manager: "javascript"
    version_requirement_updates: "increase_versions"
    directory: "/"
    update_schedule: "daily"
    automerged_updates:
      - match:
          dependency_name: "@tokenizer/range"
      - match:
          dependency_name: "@types/node"
      - match:
          dependency_name: "@types/jasmine"
      - match:
          dependency_name: "coveralls"
      - match:
          dependency_name: "karma-coverage-istanbul-reporter"
      - match:
          dependency_name: "music-metadata-browser"
      - match:
          dependency_name: "karma"
      - match:
          dependency_name: "karma-chrome-launcher"
      - match:
          dependency_name: "karma-coverage-istanbul-reporter"
      - match:
          dependency_name: "karma-firefox-launcher"
      - match:
          dependency_name: "karma-jasmine"
      - match:
          dependency_name: "karma-jasmine-html-reporter"
      - match:
          dependency_name: "karma-spec-reporter"
      - match:
          dependency_name: "karma-webpack"
      - match:
          dependency_name: "music-metadata-browser"
      - match:
          dependency_name: "istanbul-instrumenter-loader"
      - match:
          dependency_name: "tslint"
      - match:
          dependency_name: "ts-node"
      - match:
          dependency_name: "ts-loader"
      - match:
          dependency_name: "typescript"
      - match:
          dependency_name: "webpack"
      - match:
          dependency_name: "eslint"
      - match:
          dependency_name: "jasmine-core"
      - match:
          dependency_name: "del-cli"
