name: Karma CI

# Triggers the workflow on push or pull request events
on: push

jobs:

  test:
    name: 'Build & run on BrowserStack'
    runs-on: ubuntu-latest

    steps:

      - name: 'BrowserStack Env Setup'  # Invokes the setup-env action
        uses: browserstack/github-actions/setup-env@master
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - name: 'Checkout the repository'
        uses: actions/checkout@v2

      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: 'Install dependencies'
        run: yarn install

      - name: 'Code analysis (linter)'
        run: yarn run lint

      - name: 'Travis tests on BrowserStack'
        run: yarn run travis-karma-browserstack
        env:
          CI: true
