name: Karma CI
on:
  pull_request:
    paths-ignore:
      - '**.md'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: 'BrowserStack Env Setup'  # Invokes the setup-env action
        uses: browserstack/github-actions/setup-env@master
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - name: 'Checkout the repository'
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install
      - run: yarn run lint
      - run: yarn run travis-karma-browserstack
        env:
          CI: true
