name: CI browser tests

on: [push]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            browsers: 'Chrome'
#          - os: macos-latest
#            browsers: 'Safari'
#          - os: windows-latest
#            browsers: 'Edge'
    runs-on: ${{ matrix.os }}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: 'Install dependencies'
        run: yarn install

      - name: 'Compile TypeScript'
        run: yarn build

      - name: Run XVFB headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: yarn run karma-headless  --browsers ${{ matrix.browsers }}
